import { SpeedInsights } from '@vercel/speed-insights/next';
import { SessionProvider } from 'next-auth/react';
import { ThemeProvider } from 'next-themes';

import GlobalNav from '@/components/common/gnb/GlobalNav';
import ModalContainer from '@/components/common/ModalContainer';
import SonnerToast from '@/components/common/SonnerToast';
import FloatingButton from '@/components/ui/FloatingButton';

import pretendard from '../lib/utils/fonts/pretendard';

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Mogazoa (임시)',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko'>
      <body className={pretendard.variable}>
        <ThemeProvider
          attribute='class' // html 태그에 className 추가 (ex. class="dark")
          defaultTheme='system' // 기본값: OS 설정 따름
          enableSystem={true} // 시스템 다크모드 자동 감지
        >
          <SessionProvider>
            {/* 서버 컴포넌트에서 세션 정보를 가져와 클라이언트 컴포넌트에 전달 */}
            <GlobalNav />
            {children}
            <FloatingButton />
            <SonnerToast />
            <SpeedInsights />
            <ModalContainer />
          </SessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
