import { SpeedInsights } from '@vercel/speed-insights/next';
import { SessionProvider } from 'next-auth/react';

import FooterLazy from '@/components/common/Footer/FooterLazy';
import GlobalNav from '@/components/common/gnb/GlobalNav';
import ModalContainer from '@/components/common/ModalContainer';
import SonnerToast from '@/components/common/SonnerToast';
import ThemeToggle from '@/components/common/ThemeToggle';
import FloatingButton from '@/components/ui/FloatingButton';

import pretendard from '../lib/utils/fonts/pretendard';

import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Mogazoa (임시)',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='ko' className={'theme'}>
      <body className={pretendard.variable}>
        <SessionProvider>
          <GlobalNav />
          {children}
          <FooterLazy />
          <ThemeToggle />
          <FloatingButton />
          <SonnerToast />
          <SpeedInsights />
          <ModalContainer />
        </SessionProvider>
      </body>
    </html>
  );
}
