import { SpeedInsights } from '@vercel/speed-insights/next';

import ModalContainer from '@/components/common/ModalContainer';

import pretendard from '../lib/utils/fonts/pretendard';

import type { Metadata } from 'next';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className={pretendard.variable}>{children}</body>

      <SpeedInsights />
      <ModalContainer />
    </html>
  );
}
